redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\Users\\narsi\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\narsi\\public"
publishOrigin = "config"
functions = "C:\\Users\\narsi\\functions"
commandOrigin = "heuristics"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]